# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevicesDbTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=50)),
                ('deviceStatus', models.IntegerField()),
                ('raspberryId', models.IntegerField()),
            ],
        ),
    ]
